# Generated by Django 5.0.6 on 2024-07-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
